name: Build and Release luci-app-themeswitch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev gawk git gettext unzip zlib1g-dev file python3 python3-venv curl

      - name: Setup OpenWrt SDK
        run: |
          wget https://downloads.openwrt.org/releases/22.03.5/targets/x86/64/openwrt-sdk-22.03.5-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          mkdir sdk && tar -xJf openwrt-sdk-22.03.5-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz -C sdk --strip-components=1
          cd sdk
          echo "src-git packages https://github.com/openwrt/packages.git" > feeds.conf.default
          echo "src-git luci https://github.com/openwrt/luci.git" >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Add luci-app-themeswitch package
        run: |
          cd sdk/package
          git clone https://github.com/peditx/luci-app-themeswitch
          cd ..
          echo "CONFIG_PACKAGE_luci-app-themeswitch=m" >> .config

      - name: Build luci-app-themeswitch for all architectures
        run: |
          architectures=(
            x86_64
            arm_cortex-a7
            arm_cortex-a53
            arm_cortex-a72
            mips_24kc
            mipsel_24kc
            powerpc_8540
            arm_cortex-a9
            arm_xscale
            i386_pentium4
            mips_mips32
            mipsel_mips32
            powerpc_464fp
            arm_cortex-a15_neon-vfpv4
            arm_cortex-a8
            aarch64_cortex-a53
            aarch64_cortex-a72
            aarch64_generic
          )

          for arch in "${architectures[@]}"; do
            echo "Building for $arch..."
            wget https://downloads.openwrt.org/releases/22.03.5/targets/${arch}/generic/openwrt-sdk-22.03.5-${arch}_generic.Linux-x86_64.tar.xz -O sdk-${arch}.tar.xz
            mkdir -p sdk-${arch} && tar -xJf sdk-${arch}.tar.xz -C sdk-${arch} --strip-components=1
            cd sdk-${arch}
            ./scripts/feeds update -a
            ./scripts/feeds install luci-base
            make defconfig
            make package/luci-app-themeswitch/compile -j1 V=sc
            mkdir -p artifacts/${arch}
            find bin/ -name "*.ipk" -exec cp {} artifacts/${arch}/ \;
            cd ..
          done

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_id }}-$(date +%Y%m%d)
          name: luci-app-themeswitch release - ${{env.timestamp}}
          body: Latest release of luci-app-themeswitch theme for OpenWrt.
          files: sdk-${{ github.run_id }}/artifacts/*/*.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          timestamp: ${{ github.run_id }}
