name: Build luci-app-themeswitch for OpenWrt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up OpenWrt SDK
      run: |
        wget https://downloads.openwrt.org/releases/23.05.0/targets/x86/64/openwrt-sdk-23.05.0-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
        mkdir sdk && tar -xJf openwrt-sdk-23.05.0-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz -C sdk --strip-components=1
        cd sdk
        echo "src-git packages https://github.com/openwrt/packages.git" > feeds.conf.default
        echo "src-git luci https://github.com/openwrt/luci.git" >> feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Clone luci-app-themeswitch repository
      run: |
        git clone https://github.com/peditx/luci-app-themeswitch.git

    - name: Copy luci-app-themeswitch package
      run: |
        cp -r luci-app-themeswitch ./sdk/package/

    - name: Set default configuration
      run: |
        cd sdk
        make defconfig

    - name: Build lucihttp for all architectures
      run: |
        cd sdk
        for target in $(ls -1 target/linux); do
          if [ -d "target/linux/$target" ]; then
            echo "Building lucihttp for target: $target"
            make TOOLCHAIN=1 TARGET=$target package/feeds/luci/lucihttp/compile V=s
          fi
        done

    - name: Build luci-app-themeswitch for all architectures
      run: |
        cd sdk
        for target in $(ls -1 target/linux); do
          if [ -d "target/linux/$target" ]; then
            echo "Building luci-app-themeswitch for target: $target"
            make TOOLCHAIN=1 TARGET=$target package/luci-app-themeswitch/compile V=s
          fi
        done

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: luci-app-themeswitch-ipk
        path: sdk/bin/packages/*/base/luci-app-themeswitch*.ipk
