name: Build luci-app-themeswitch for OpenWrt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [23.05]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up OpenWrt build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache git subversion libncurses5-dev zlib1g-dev gawk flex quilt xsltproc libssl-dev wget unzip python3 python3-venv

    - name: Set up OpenWrt SDK
      run: |
        wget https://downloads.openwrt.org/releases/23.05.0/targets/x86/64/openwrt-sdk-23.05.0-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
        mkdir sdk && tar -xJf openwrt-sdk-23.05.0-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz -C sdk --strip-components=1
        cd sdk
        echo "src-git packages https://github.com/openwrt/packages.git" > feeds.conf.default
        echo "src-git luci https://github.com/openwrt/luci.git" >> feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Clone luci-app-themeswitch repository
      run: |
        git clone https://github.com/peditx/luci-app-themeswitch.git

    - name: Copy luci-app-themeswitch package
      run: |
        cp -r luci-app-themeswitch ./sdk/package/

    - name: Build OpenWrt
      run: |
        cd sdk
        ./scripts/feeds install luci-app-themeswitch
        make defconfig
        make -j$(nproc)

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: openwrt-build
        path: sdk/bin/
